### PR TITLE
Adding Deena's card 

### PR DESCRIPTION
**Pull request by stitchandmax23**

### CODE REVIEW

**Review by shanecs — APPROVED** [review]
lgtm

**Comment by KenKay327** [comment]
Why do you hurt me?

**Comment by KenKay327** [comment]
WHY DID YOU LEAVE ME

**Comment by KenKay327** [comment]
respond

**Comment by KenKay327** [comment]
I know you see this

**Comment by stitchandmax23** [comment]
I do see this but i tend to ignore it

**Comment by KenKay327** [comment]
omg like why Apprentice

**Comment by KenKay327** [comment]
This is like

**Comment by KenKay327** [comment]
Stressful

**Comment by stitchandmax23** [comment]
Cuz i have more important things to worry about

**Comment by KenKay327** [comment]
Hey I'm important like dood I like m8

**Comment by stitchandmax23** [comment]
whta's m8

**Comment by KenKay327** [comment]
Sound it out

**Comment by KenKay327** [comment]
Hit or miss

**Comment by stitchandmax23** [comment]
i guess they never miss huh? u got a boyfriend i bet he doesn't kiss huh

**Comment by KenKay327** [comment]
GDBGSJFHAKGHKLJSFGHSAKJFGHSILFGDH

**Comment by KenKay327** [comment]
tHAT WAS TARGETED AT ME HFDHBFNGH

**Comment by stitchandmax23** [comment]
YEP!

**Comment by KenKay327** [comment]
wELL I BET hee Does'nt KISS you

**Comment by stitchandmax23** [comment]
Cuz he lives far from chicago

**Comment by KenKay327** [comment]
'Cause he fat gurl

**Comment by KenKay327** [comment]
He's the wall between Mexico

**Comment by stitchandmax23** [comment]
and not able to leave the country

**Comment by stitchandmax23** [comment]
He lives in Morocco

**Comment by KenKay327** [comment]
Ya you better run

**Comment by KenKay327** [comment]
Go first

**Comment by KenKay327** [comment]
I trained you for this

**Comment by stitchandmax23** [comment]
YOU DIDNT TRAIN ME FOR ANYTHING

**Comment by KenKay327** [comment]
I did

**Comment by KenKay327** [comment]
You just didn't believe in the magic

**Comment by KenKay327** [comment]
Go now apprentice

**Comment by stitchandmax23** [comment]
I believe in magic like harry potter and ron weasley and Hermoinie granger.

**Comment by KenKay327** [comment]
I was Dombledor

**Comment by KenKay327** [comment]
And the other tough guy

**Comment by stitchandmax23** [comment]
YOUR NOT TOUGH YOUR WEAK

**Comment by KenKay327** [comment]
You wanna test that out M8

**Comment by stitchandmax23** [comment]
NAH CUZ IM STRONGER THAN YOU

**Comment by KenKay327** [comment]
yEAAHHH

**Comment by KenKay327** [comment]
sure

**Comment by stitchandmax23** [comment]
It's true

**Comment by stitchandmax23** [comment]
I can beat up my brother

**Comment by KenKay327** [comment]
He's 11 your 15 of course you can

**Comment by KenKay327** [comment]
That's like saying you can beat up an infant

**Comment by stitchandmax23** [comment]
I can beat u up to ur younger than me so

**Comment by KenKay327** [comment]
LMAO

**Comment by KenKay327** [comment]
I'm CRYING

**Comment by stitchandmax23** [comment]
LMAO

**Comment by KenKay327** [comment]
Hey

**Comment by KenKay327** [comment]
are you gonna say sorry

**Comment by KenKay327** [comment]
Ur phone gae

**Comment by stitchandmax23** [comment]
Hey! Sorry I just saw this message!

**Comment by stitchandmax23** [comment]
Excuse me?! Your phone is gay

**Pull request merged**
